// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayFlow.Infrastructure.Persistence;

#nullable disable

namespace PayFlow.Infrastructure.Migrations
{
    [DbContext(typeof(PayFlowDbContext))]
    partial class PayFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayFlow.Domain.Entities.Cobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceladaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PagaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_cobrancas_status_pendente")
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("cobrancas", (string)null);
                });

            modelBuilder.Entity("PayFlow.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CobrancaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoTransacao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstornadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RecusadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CobrancaId")
                        .HasDatabaseName("ix_pagamentos_cobranca_id");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("PayFlow.Domain.Entities.Cobranca", b =>
                {
                    b.OwnsOne("PayFlow.Domain.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("CobrancaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("valor");

                            b1.HasKey("CobrancaId");

                            b1.ToTable("cobrancas");

                            b1.WithOwner()
                                .HasForeignKey("CobrancaId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("PayFlow.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("PayFlow.Domain.Entities.Cobranca", null)
                        .WithMany("Pagamentos")
                        .HasForeignKey("CobrancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PayFlow.Domain.Entities.Cobranca", b =>
                {
                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
